name: DeployProduction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup
    - name: Deploy
      uses: ./.github/actions/deploy
      with:
        herokuApiKey: ${{ secrets.HEROKU_API_KEY }}
        herokuAppName: ${{ secrets.HEROKU_APP_NAME__PRODUCTION }}
        herokuEmail: ${{ secrets.HEROKU_EMAIL }}
